# Generated by Django 5.0.7 on 2024-11-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(max_length=50)),
                ('mail_departement', models.EmailField(max_length=254)),
                ('numero_departement', models.CharField(max_length=50)),
            ],
        ),
    ]
