# Generated by Django 5.0.7 on 2024-11-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departementmodel',
            table='departement',
        ),
    ]
