# Generated by Django 5.0.7 on 2024-11-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_alter_departementmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='departementmodel',
            name='description_departement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
