# Generated by Django 5.1.4 on 2024-12-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0003_departementmodel_description_departement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departementmodel',
            options={'verbose_name_plural': 'Departements'},
        ),
    ]
