# Generated by Django 5.1.4 on 2025-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0004_alter_departementmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesseurModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_prof', models.CharField(max_length=50)),
                ('date_d_adhesion', models.DateTimeField()),
                ('chef_departement', models.ManyToManyField(to='departement.departementmodel')),
            ],
        ),
    ]
