# Generated by Django 5.1.4 on 2025-01-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0005_professeurmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professeurmodel',
            options={'verbose_name_plural': 'Professeurs'},
        ),
        migrations.AlterField(
            model_name='professeurmodel',
            name='date_d_adhesion',
            field=models.DateField(),
        ),
    ]
