# Generated by Django 5.1.4 on 2025-01-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0006_alter_professeurmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeurmodel',
            name='nom_prof',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
