# Generated by Django 5.1.4 on 2025-01-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0008_alter_professeurmodel_chef_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeurmodel',
            name='contact_prof',
            field=models.CharField(max_length=50, verbose_name='Contact professeur'),
        ),
        migrations.AlterField(
            model_name='professeurmodel',
            name='date_d_adhesion',
            field=models.DateField(verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='professeurmodel',
            name='nom_prof',
            field=models.CharField(max_length=50, verbose_name='Nom complet du professeur'),
        ),
    ]
