# Generated by Django 5.1.4 on 2025-01-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0009_alter_professeurmodel_contact_prof_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professeurmodel',
            table='professeur',
        ),
    ]
